# Generated by Django 3.0.7 on 2020-08-19 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_remove_customuser_alamat_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_gabung', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-nama'],
            },
        ),
        migrations.CreateModel(
            name='TimMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_gabung', models.DateField()),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Mapel')),
            ],
        ),
        migrations.AddField(
            model_name='mapel',
            name='tim_mapel',
            field=models.ManyToManyField(through='account_app.TimMapel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.IntegerField()),
                ('nama', models.CharField(max_length=20)),
                ('anggota_kelas', models.ManyToManyField(through='account_app.AnggotaKelas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tingkat'],
            },
        ),
        migrations.AddField(
            model_name='anggotakelas',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Kelas'),
        ),
        migrations.AddField(
            model_name='anggotakelas',
            name='murid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
