# Generated by Django 3.0.7 on 2020-08-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_auto_20200819_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggotakelas',
            options={'ordering': ['murid']},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'ordering': ['tingkat']},
        ),
        migrations.AlterModelOptions(
            name='mapel',
            options={'ordering': ['nama']},
        ),
        migrations.AlterModelOptions(
            name='timmapel',
            options={'ordering': ['mapel']},
        ),
    ]
