# Generated by Django 3.0.7 on 2020-08-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_auto_20200820_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggotakelas',
            options={'ordering': ['murid'], 'verbose_name_plural': 'Murid'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'ordering': ['tingkat'], 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='mapel',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='timmapel',
            options={'ordering': ['mapel'], 'verbose_name_plural': 'Guru'},
        ),
        migrations.AddField(
            model_name='kelas',
            name='guru_pembina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guru_pembina', to='account_app.TimMapel'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='ketua_murid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_murid', to='account_app.AnggotaKelas'),
        ),
    ]
