# Generated by Django 3.0.7 on 2020-08-28 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20200822_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat_pengajaran', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(max_length=1000)),
                ('tanggal_buat', models.DateField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Mapel')),
            ],
            options={
                'verbose_name_plural': 'Kurikulum',
                'ordering': ['mapel'],
            },
        ),
        migrations.AlterModelOptions(
            name='anggotakelas',
            options={'ordering': ['kelas', 'murid__nama_lengkap'], 'verbose_name_plural': 'Murid'},
        ),
        migrations.CreateModel(
            name='LogMengajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(max_length=1000)),
                ('tanggal_buat', models.DateField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Kelas')),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Kurikulum')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Mapel')),
            ],
            options={
                'verbose_name_plural': 'Log Mengajar',
                'ordering': ['tanggal_buat'],
            },
        ),
    ]
