# Generated by Django 3.0.7 on 2020-08-29 05:21

from django.db import migrations
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20200828_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurikulum',
            name='deskripsi',
            field=editorjs_field.fields.EditorJSField(),
        ),
    ]
