# Generated by Django 3.0.7 on 2020-08-29 05:44

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_auto_20200829_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurikulum',
            name='deskripsi',
            field=quilljs.fields.RichTextField(),
        ),
    ]
