# Generated by Django 3.0.7 on 2020-08-29 21:55

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_auto_20200830_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmengajar',
            name='mapel',
        ),
        migrations.AlterField(
            model_name='logmengajar',
            name='deskripsi',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='logmengajar',
            name='tanggal_buat',
            field=models.DateTimeField(),
        ),
    ]
