# Generated by Django 3.0.7 on 2020-08-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('konten', models.TextField(max_length=1000)),
                ('kategori', models.CharField(choices=[('Guru', 'Guru'), ('Murid', 'Murid')], max_length=10)),
                ('waktu_post', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['waktu_post'],
            },
        ),
    ]
