# Generated by Django 3.0.7 on 2020-08-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengumuman',
            options={'ordering': ['waktu_post'], 'verbose_name_plural': 'Pengumuman'},
        ),
    ]
