# Generated by Django 3.0.7 on 2020-08-23 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20200822_1002'),
        ('extra_app', '0002_auto_20200822_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiMurid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('deskripsi', models.CharField(max_length=300)),
                ('nilai', models.FloatField()),
                ('mapel_tes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Mapel')),
                ('pembuat_tes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.TimMapel')),
                ('peserta_tes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.AnggotaKelas')),
            ],
            options={
                'verbose_name_plural': 'Nilai Murid',
                'ordering': ['peserta_tes'],
            },
        ),
    ]
