# Generated by Django 3.0.7 on 2020-08-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20200822_1002'),
        ('extra_app', '0003_nilaimurid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimurid',
            name='mapel_tes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Mapel', verbose_name='Mata Pelajaran'),
        ),
        migrations.AlterField(
            model_name='nilaimurid',
            name='pembuat_tes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.TimMapel', verbose_name='Penilai'),
        ),
        migrations.AlterField(
            model_name='nilaimurid',
            name='peserta_tes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.AnggotaKelas', verbose_name='Peserta Tes'),
        ),
        migrations.CreateModel(
            name='LaporanMurid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('konten', models.TextField(max_length=1000)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.TimMapel', verbose_name='Guru')),
                ('terlapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.AnggotaKelas', verbose_name='Murid')),
            ],
            options={
                'verbose_name_plural': 'Laporan Murid',
                'ordering': ['terlapor'],
            },
        ),
    ]
