# Generated by Django 3.0.7 on 2020-08-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20200822_1002'),
        ('extra_app', '0004_auto_20200823_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagihanMurid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('nilai', models.IntegerField()),
                ('status_bayar', models.BooleanField(blank=True, null=True)),
                ('waktu_bayar', models.DateTimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, max_length=500, null=True)),
                ('tertagih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.AnggotaKelas', verbose_name='Murid')),
            ],
            options={
                'verbose_name_plural': 'Tagihan Murid',
                'ordering': ['tertagih'],
            },
        ),
    ]
