# Generated by Django 3.0.7 on 2020-08-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0005_tagihanmurid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporanmurid',
            options={'ordering': ['-waktu'], 'verbose_name_plural': 'Laporan Murid'},
        ),
        migrations.AlterModelOptions(
            name='nilaimurid',
            options={'ordering': ['mapel_tes'], 'verbose_name_plural': 'Nilai Murid'},
        ),
        migrations.AlterModelOptions(
            name='pengumuman',
            options={'ordering': ['-waktu_post'], 'verbose_name_plural': 'Pengumuman'},
        ),
        migrations.AlterModelOptions(
            name='tagihanmurid',
            options={'ordering': ['status_bayar'], 'verbose_name_plural': 'Tagihan Murid'},
        ),
    ]
